<?php


namespace App\Enums\Common;


class FasPolicyParam
{
    public CONST BUDGET_EST_CONCURRED_AMOUNT_ENTRY_ALLOWED = 0;
    public CONST BUDGET_EST_CURRENT_YEAR_AMOUNT_ENTRY_ALLOWED = 0;
    public CONST BUDGET_EST_LAST_YEAR_PROVISION_ENTRY_ALLOWED = 0;
    public CONST LIVE_IMPLIMENTATION_STATUS = 1;
    public CONST LIVE_IMPLIMENTATION_STATUS_ON = 1;
    public CONST LIVE_IMPLIMENTATION_STATUS_OFF = 0;
    public CONST BILL_PAYMENT_ENTRY_WITHOUT_CHEQUE_VALIDATION = 0;
    public CONST CLEARING_RECONCILIATION_ENTRY_REALTIME = 1;
}
