--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, 
--     DPT_DIVISION_ID, FIN_CODE
--  FROM SBCACC.L_DEPARTMENT
--  ORDER BY 2 ASC NULLS LAST;
--
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(1, 'MARINE', 'মেরিন', 5, '90390');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(2, 'HYDROGRAPHY', 'হাইড্রোগ্রাফি', 5, '90010');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(3, 'MARINE ENGINEERING', 'মেরিন ওয়ার্কশপ ', 5, '90740');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(4, 'ELECTRICAL', 'বৈদ্যুতিক', 3, '90720');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(5, 'CIVIL ENGINEERING', 'প্রকৌশল বিভাগ', 3, '90630');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(6, 'STORE', 'ভাণ্ডার', 3, '90590');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(8, 'FINANCE & ACCOUNTS', 'অর্থ ও হিসাব', 2, '90480');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(9, 'AUDIT & INSPECTION', 'নিরীক্ষা ও পরিদর্শন', 2, '90490');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(10, 'COMPUTER CENTER', 'কম্পিউটার কেন্দ্র', 2, '90810');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(11, 'ADMINISTRATION', 'প্রশাসন', 4, '90470');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(12, 'SECRETARIAT', 'সেক্রেটারি', 4, '90460');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(13, 'PLANNING', 'পরিকল্পনা', 4, '90540');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(14, 'MEDICAL', 'চিকিৎসা', 4, '90560');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(15, 'TRAFFIC', 'ট্রাফিক', 1, '90200');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(16, 'SECURITY', 'নিরাপত্তা', 1, '90550');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(18, 'MECHANICAL', 'মেকানিক্যাল', 3, '90730');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(19, 'ESTATE AFFAIRS', 'ভূমি', 3, '90521');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(19, 'ESTATE AFFAIRS', 'ভূমি', 3, '90631');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(19, 'ESTATE BRANCH', NULL, 3, '90520');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(20, 'BOARD', 'বোর্ড', 6, '90450');
Insert into SBCACC.L_DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_NAME_BNG, DPT_DIVISION_ID, FIN_CODE)
Values
(21, 'FIRE SERVICE', NULL, 1, '90510');
COMMIT;
